# Generated by Django 4.0 on 2022-01-14 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='firmstoredata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrdatafirm', models.ImageField(blank=True, null=True, upload_to='qrcode_firm')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firm.firm')),
            ],
        ),
    ]
