# Generated by Django 4.0 on 2022-01-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firm', '0002_firmstoredata'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmstoredata',
            name='data',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='firmstoredata',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='firmpdfdata'),
        ),
    ]
