# Generated by Django 3.2.7 on 2022-02-04 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firm', '0003_firmstoredata_data_firmstoredata_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmstoredata',
            name='datescanned',
            field=models.DateField(default=datetime.date(2022, 2, 4)),
        ),
        migrations.AlterField(
            model_name='firmstoredata',
            name='data',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
