# Generated by Django 3.2.7 on 2022-02-04 11:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firm', '0004_auto_20220204_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='tempqrstore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrdata', models.ImageField(blank=True, null=True, upload_to='qrtempcode')),
                ('datescanned', models.DateField(default=datetime.date(2022, 2, 4))),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firm.firm')),
            ],
        ),
    ]
