# Generated by Django 4.0 on 2022-02-12 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firm', '0005_tempqrstore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmstoredata',
            name='datescanned',
            field=models.DateField(default=datetime.date(2022, 2, 12)),
        ),
        migrations.AlterField(
            model_name='tempqrstore',
            name='datescanned',
            field=models.DateField(default=datetime.date(2022, 2, 12)),
        ),
    ]
