# Generated by Django 4.0 on 2022-03-03 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firm', '0006_alter_firmstoredata_datescanned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmstoredata',
            name='datescanned',
            field=models.DateField(default=datetime.date(2022, 3, 3)),
        ),
        migrations.AlterField(
            model_name='tempqrstore',
            name='datescanned',
            field=models.DateField(default=datetime.date(2022, 3, 3)),
        ),
    ]
