# Generated by Django 3.2.7 on 2022-03-06 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firm', '0007_alter_firmstoredata_datescanned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firmstoredata',
            name='qrdatafirm',
        ),
        migrations.AlterField(
            model_name='firmstoredata',
            name='datescanned',
            field=models.DateField(default=datetime.date(2022, 3, 6)),
        ),
        migrations.AlterField(
            model_name='tempqrstore',
            name='datescanned',
            field=models.DateField(default=datetime.date(2022, 3, 6)),
        ),
    ]
