# Generated by Django 4.0 on 2022-03-10 05:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firm', '0008_auto_20220306_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmstoredata',
            name='datescanned',
            field=models.DateField(default=datetime.date(2022, 3, 10)),
        ),
        migrations.AlterField(
            model_name='tempqrstore',
            name='datescanned',
            field=models.DateField(default=datetime.date(2022, 3, 10)),
        ),
    ]
