# Generated by Django 4.0 on 2022-04-12 01:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firm', '0009_alter_firmstoredata_datescanned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmstoredata',
            name='datescanned',
            field=models.DateField(default=datetime.date(2022, 4, 12)),
        ),
        migrations.AlterField(
            model_name='tempqrstore',
            name='datescanned',
            field=models.DateField(default=datetime.date(2022, 4, 12)),
        ),
    ]
