# Generated by Django 3.2.7 on 2021-12-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('pwd', models.CharField(max_length=30)),
                ('contactno', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
