# Generated by Django 4.0 on 2022-01-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_clientdataqrexe2_todaydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='adhar',
            field=models.CharField(default='000000000000', max_length=12),
        ),
    ]
