# Generated by Django 4.0 on 2022-01-13 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_clientdataqrexe2_todaydate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='clientdocument',
        ),
    ]
