# Generated by Django 4.0 on 2022-01-13 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_delete_clientdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientdocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdfdata', models.FileField(blank=True, null=True, upload_to='documents')),
                ('qrdata', models.ImageField(upload_to='qrcode')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.clientdataqrexe2')),
            ],
        ),
    ]
