# Generated by Django 4.0 on 2022-01-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_clientdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdocument',
            name='qrdata',
            field=models.FileField(blank=True, null=True, upload_to='qrcode'),
        ),
    ]
