# Generated by Django 4.0 on 2022-01-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_alter_clientdocument_qrdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdocument',
            name='qrdata',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode'),
        ),
    ]
