# Generated by Django 3.2.7 on 2022-03-06 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0021_remove_clientdataqrexe2_symptoms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdataqrexe2',
            name='todaydate',
            field=models.DateField(default=datetime.date(2022, 3, 6)),
        ),
    ]
