# Generated by Django 4.0 on 2022-03-10 05:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0022_alter_clientdataqrexe2_todaydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdataqrexe2',
            name='todaydate',
            field=models.DateField(default=datetime.date(2022, 3, 10)),
        ),
    ]
